### ISSUE TITLE
2 repos with similar names.

### ISSUE THREAD

**Issue by rahlk** [asaha1/x9115arn#1]
@asaha1 
There are 2 repos with same author and suffix: 
- https://github.com/asaha1/x9115arn (_this one_)
- https://github.com/arnabsaha1011/x9115arn

**Comment by asaha1** [comment]
Hey Rahul,
Sorry for the confusion. I have removed timm and rahlk as collaborators
from arnabsaha1011/x9115arn. I'll be using the asaha1 account.

**Comment by rahlk** [comment]
Thanks!
